[workspace]
members = [
    "benchmarks/aunt-kg/",
    "benchmarks/fizzbuzz/",
    "benchmarks/logic-query/",
    "benchmarks/oeis/",
    "experiments/expr/bytestring/",
    "experiments/expr/dyck/", "experiments/morkl_interpreter", "experiments/symbol_mapping/bucket_map", "experiments/symbol_mapping/naive_map",
    "frontend/",
    "server",
    "kernel/"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]

# Internal to MORK
mork-bytestring = {path = "./experiments/expr/bytestring"}
mork-frontend = {path = "./frontend"}
mork = {path = "./kernel"}

# External to MORK
# pathmap = {path = "../PathMap" , features = ["all_dense_nodes"]}
[workspace.dependencies.pathmap]
path = "../PathMap"
features = ["jemalloc"]
# features = ["jemalloc", "all_dense_nodes"]
